### ISSUE TITLE
[curl] SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by eif0** [ekingery/hushmail-automatic-login#4]
First fo all, thank you so much for sharing this script, it's awesome!! It's been working great for a while, but today I got an error:

> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.
> rm: cannot remove â€˜/tmp/hush_cookies.txtâ€™: No such file or directory
> login failed with results:

As a side note, I haven't updated anything in the OS.

**Comment by ekingery** [comment]
Cool, glad it's been helpful. I am unable to reproduce this problem. Can you try from another network or computer? Below are a couple of possibly related links, it looks to me like this is unrelated to the script. For some reason on your computer curl is rejecting the cert chain used to access hushmail.

http://www.cambus.net/installing-ca-certificates-on-netbsd/
https://github.com/wayneeseguin/rvm/issues/2208
